 
 const data = [{
    id: 'NLEJ7gxOak',
    title: 'Most stockmarket returns come from a tiny fraction of shares',
    description: 'Facebook, Amazon, Apple, Netflix and Google (FAANG) have been the motor of the S&P 500',
    authors: null,
    slug: 'most-stockmarket-returns-come-from-a-tiny-fraction-of-shares-4212887524',
    url: 'https://www.economist.com/finance-and-economics/2018/06/23/most-stockmarket-returns-come-from-a-tiny-fraction-of-shares',
    mobile_url: null,
    image_url: 'https://www.economist.com/assets/the-economist-logo.png',
    published_at: '2018-06-23T00:00:00.000Z',
    site: {
      id: 'z28aeDEnRm',
      name: 'The Economist',
      slug: null,
      language: 'en',
      hostname: 'www.economist.com',
      url: 'http://www.economist.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 814,
    read_time: 180,
    created: '2018-06-21T18:29:50.104Z',
    score: 84.80139,
  }, {
    id: '1qEyB45zaB',
    title: 'Google, Facebook, Apple, Amazon may pay more to operate in Sunnyvale',
    description: 'Companies that are currently in Sunnyvale, such as Apple, Google and Amazon could be obliged to confront higher per-employee taxes under a plan now circulating in the South Bay city.',
    authors: ['George Avalos'],
    slug: 'google-facebook-apple-amazon-may-pay-more-to-operate-in-sunnyvale-2806969049',
    url: 'https://www.mercurynews.com/2018/06/06/google-facebook-apple-amazon-pay-tax-operate-jobs-sunnyvale/',
    mobile_url: null,
    image_url: 'https://www.mercurynews.com/wp-content/uploads/2018/06/SJM-L-SUNNYTAX-0607-0.jpg',
    published_at: '2018-06-06T19:40:43.000Z',
    site: {
      id: 'q4m6b8WElx',
      name: 'The Mercury News',
      slug: null,
      language: 'en',
      hostname: 'www.mercurynews.com',
      url: 'http://www.mercurynews.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 639,
    read_time: 120,
    created: '2018-06-09T05:08:18.631Z',
    score: 79.88783,
  }, {
    id: '2ZakjpqNE1',
    title: "AT&T finished its $81bn takeover of Warner Bros two days after the judge's approval- Technology News, Firstpost",
    description: 'AT&T plans to compete against the likes of Amazon, Google and Netflix.',
    authors: ['The Associated Press'],
    slug: 'at-and-t-finished-its-81bn-takeover-of-warner-bros-two-days-after-the-judges-approval-technology-news-firstpost-123953252',
    url: 'https://www.firstpost.com/tech/news-analysis/att-finished-its-81bn-takeover-of-warner-bros-two-days-after-the-judges-approval-4525561.html',
    mobile_url: null,
    image_url: 'https://images.firstpost.com/wp-content/uploads/2018/01/RTX3CV0C.jpg',
    published_at: '2018-06-17T04:58:55.000Z',
    site: {
      id: '4mBaoROEAY',
      name: 'Firstpost',
      slug: null,
      language: 'en',
      hostname: 'www.firstpost.com',
      url: 'http://www.firstpost.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 572,
    read_time: 120,
    created: '2018-06-17T11:25:26.805Z',
    score: 70.70124,
  }, {
    id: '3561JA50Go',
    title: 'Amazon employees demand company cut ties with ICE',
    description: 'Their call follows employee-driven campaigns at Microsoft and Google, where workers have denounced projects that provide technology to ICE and to military operations.',
    authors: ['Hamza Shaban'],
    slug: 'amazon-employees-demand-company-cut-ties-with-ice-1297145711',
    url: 'https://www.washingtonpost.com/news/the-switch/wp/2018/06/22/amazon-employees-demand-company-cut-ties-with-ice/',
    mobile_url: null,
    image_url: 'https://www.washingtonpost.com/resizer/XE4_vfg0hPubBESi9j59EPXb24I=/1484x0/arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/WYDY3COJNE4DBG6QD6NBHIJGHA.jpg',
    published_at: '2018-06-22T20:24:27.000Z',
    site: {
      id: '3yN6dqG5KB',
      name: 'The Washington Post',
      slug: null,
      language: 'en',
      hostname: 'www.washingtonpost.com',
      url: 'https://www.washingtonpost.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 537,
    read_time: 120,
    created: '2018-06-22T22:51:58.573Z',
    score: 65.033424,
  }, {
    id: 'NXGwelNvaY',
    title: 'Why FANG stocks are hitting record highs despite US-China trade fights',
    description: 'Facebook, Netflix and the tech-heavy Nasdaq index hit record highs on Wednesday.',
    authors: ['Arjun Kharpal'],
    slug: 'why-fang-stocks-are-hitting-record-highs-despite-us-china-trade-fights-1610295314',
    url: 'https://www.cnbc.com/2018/06/21/why-fang-stocks-are-hitting-record-highs-despite-us-china-trade-fights.html',
    mobile_url: null,
    image_url: 'https://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2018/05/01/105175286-GettyImages-953382756.1910x1000.jpg',
    published_at: '2018-06-21T09:55:39.000Z',
    site: {
      id: 'VelG95qGW5',
      name: 'CNBC',
      slug: null,
      language: 'en',
      hostname: 'www.cnbc.com',
      url: 'http://www.cnbc.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 532,
    read_time: 120,
    created: '2018-06-21T21:00:50.381Z',
    score: 61.364548,
  }, {
    id: 'dNx6QyO62L',
    title: 'Netflix, Microsoft, and Google just quietly changed how the web works',
    description: 'The organization that sets standards for the web just failed to beat back a stupid, greedy technology.',
    authors: ['Adrianne Jeffries'],
    slug: 'netflix-microsoft-and-google-just-quietly-changed-how-the-web-works-4086441722',
    url: 'https://theoutline.com/post/2304/netflix-microsoft-and-google-just-quietly-changed-how-the-web-works',
    mobile_url: null,
    image_url: 'https://outline-prod.imgix.net/20170921-1ijqyUebIit8lMLSnggn',
    published_at: '2017-09-21T14:36:00.000Z',
    site: {
      id: 'wgDEnvkEJA',
      name: 'The Outline',
      slug: null,
      language: 'en',
      hostname: 'theoutline.com',
      url: 'https://theoutline.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1749,
    read_time: 360,
    created: '2018-06-05T23:04:17.185Z',
    score: 60.81597,
  }, {
    id: '5KGXvjpkaA',
    title: 'Twitter acquires anti-abuse technology provider Smyte',
    description: 'Twitter this morning announced it has agreed to buy San Francisco-based technology company Smyte, which describes itself as “trust and safety as a service.” Founded in 2014 by former Google and Instagram engineers, Smyte offers tools to stop online abuse, harassment, and spam, and protect user accounts. Terms of the deal were not disclosed, but thi',
    authors: ['Sarah Perez'],
    slug: 'twitter-acquires-anti-abuse-technology-provider-smyte-3154506676',
    url: 'https://techcrunch.com/2018/06/21/twitter-acquires-anti-abuse-technology-provider-smyte/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2017/01/twitter-ban-speech.png',
    published_at: '2018-06-21T03:02:32.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 801,
    read_time: 180,
    created: '2018-06-21T13:20:35.026Z',
    score: 58.955154,
  }, {
    id: 'yN6dopza5K',
    title: 'Tech’s Titans Tiptoe Toward Monopoly',
    description: 'Will Facebook, Google and Amazon be regulated or broken up like Standard Oil and AT&T? It depends on how they grow, writes Christopher Mims.',
    authors: ['Christopher Mims'],
    slug: 'techs-titans-tiptoe-toward-monopoly-87886255',
    url: 'https://www.wsj.com/articles/techs-titans-tiptoe-toward-monopoly-1527783845',
    mobile_url: null,
    image_url: 'https://si.wsj.net/public/resources/images/B3-AQ159_KEYWOR_SOC_20180531125330.jpg',
    published_at: '2018-05-31T16:24:00.000Z',
    site: {
      id: 'k3561Y6o2l',
      name: 'The Wall Street Journal',
      slug: null,
      language: 'en',
      hostname: 'www.wsj.com',
      url: 'https://www.wsj.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1182,
    read_time: 240,
    created: '2018-06-05T23:09:44.469Z',
    score: 56.297035,
  }, {
    id: 'QmDGzKYENl',
    title: 'I invested early in Google and Facebook. Now they terrify me.',
    description: 'The growing Internet monopolies have grabbed so much of our attention that they are a menace to public health and democracy.',
    authors: ['Roger McNamee', 'Opinion contributor'],
    slug: 'i-invested-early-in-google-and-facebook-now-they-terrify-me-2731203877',
    url: 'https://www.usatoday.com/story/opinion/2017/08/08/my-google-and-facebook-investments-made-fortune-but-now-they-menace/543755001/',
    mobile_url: null,
    image_url: 'https://www.gannett-cdn.com/-mm-/ad80e9ce8b9d45da44c6931cf7fa35770637e9be/c=0-553-5992-3938&r=x1683&c=3200x1680/local/-/media/2017/08/07/USATODAY/USATODAY/636377032036647378-AP-FACEBOOK-92616617.JPG',
    published_at: '2017-08-08T07:15:02.472Z',
    site: {
      id: 'VelG9y8GW5',
      name: 'USA Today',
      slug: null,
      language: 'en',
      hostname: 'www.usatoday.com',
      url: 'http://www.usatoday.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 892,
    read_time: 180,
    created: '2018-06-05T23:04:01.986Z',
    score: 56.215622,
  }, {
    id: 'w2EWxOZVae',
    title: 'Amazon Workers Demand Jeff Bezos Cancel Face Recognition Contracts With Law Enforcement',
    description: 'Following employee protests at Google and Microsoft over government contracts, workers at Amazon are circulating an internal letter to CEO Jeff Bezos, asking him to stop selling the company’s Rekognition facial recognition software to law enforcement and to boot the data-mining firm Palantir from its cloud services.',
    authors: ['Kate Conger'],
    slug: 'amazon-workers-demand-jeff-bezos-cancel-face-recognition-contracts-with-law-enforcement-3587880057',
    url: 'https://gizmodo.com/amazon-workers-demand-jeff-bezos-cancel-face-recognitio-1827037509',
    mobile_url: null,
    image_url: 'https://i.kinja-img.com/gawker-media/image/upload/s--SO97yNll--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/jisipsq6ktedkeynkmhh.jpg',
    published_at: '2018-06-22T01:22:00.000Z',
    site: {
      id: 'z28ae8gEnR',
      name: 'Gizmodo',
      slug: null,
      language: 'en',
      hostname: 'gizmodo.com',
      url: 'http://gizmodo.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1210,
    read_time: 240,
    created: '2018-06-22T11:00:08.619Z',
    score: 51.507965,
  }, {
    id: 'Bx6mkYR5Eg',
    title: 'U.S. senator questions Alphabet, Twitter on Huawei relationship',
    description: 'A U.S. senator on Thursday is seeking responses from Google parent Alphabet Inc and Twitter Inc on whether the U.S. companies have any data sharing agreements with Chinese vendors, following a disclosure from Facebook Inc this week.',
    authors: ['David Shepardson'],
    slug: 'u-s-senator-questions-alphabet-twitter-on-huawei-relationship-2854277886',
    url: 'https://www.reuters.com/article/us-usa-tech-huawei/u-s-senator-questions-alphabet-twitter-on-huawei-relationship-idUSKCN1J32I4',
    mobile_url: null,
    image_url: 'https://s4.reutersmedia.net/resources/r/',
    published_at: '2018-06-07T18:10:58.000Z',
    site: {
      id: 'wRdG0w6g0M',
      name: 'Reuters',
      slug: null,
      language: 'en',
      hostname: 'www.reuters.com',
      url: 'http://www.reuters.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 398,
    read_time: 60,
    created: '2018-06-07T21:21:05.864Z',
    score: 50.75757,
  }, {
    id: 'wxaOxRKK6l',
    title: 'Google, Microsoft, Amazon: Are they responsible for government use?',
    description: 'Welcome to the world of politicized capitalism doused with hashtag activism.',
    authors: ['Larry Dignan'],
    slug: 'google-microsoft-amazon-are-they-responsible-for-government-use-2411585020',
    url: 'https://www.zdnet.com/article/google-microsoft-amazon-are-they-responsible-for-government-use/',
    mobile_url: null,
    image_url: 'https://zdnet4.cbsistatic.com/hub/i/r/2018/06/19/a6ffd1c7-7be2-4a37-8b79-3d2cf683f7d5/thumbnail/770x578/1b6f073c4fbadcac0ea9d87e745795f6/1.jpg',
    published_at: '2018-06-20T11:00:00.000Z',
    site: {
      id: 'VelG98r6W5',
      name: 'ZD Net',
      slug: null,
      language: 'en',
      hostname: 'www.zdnet.com',
      url: 'http://www.zdnet.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1134,
    read_time: 240,
    created: '2018-06-20T14:40:12.564Z',
    score: 49.82451,
  }, {
    id: 'LqEZDKbr6g',
    title: 'Is insurance a rich enough game to disrupt?',
    description: 'For the last decade, the largest technology companies have increasingly looked outside of tech to grow their operations. Now, companies like Apple and Google and Amazon are eyeing innovation across the insurance landscape.',
    authors: ['David Riggs', 'Martha Notaras'],
    slug: 'Is-insurance-a-rich-enough-game-to-disrupt-Uj4qPiI',
    url: 'https://techcrunch.com/2018/07/10/is-insurance-a-rich-enough-game-to-disrupt/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2016/04/insurance-e1530627709458.jpg?w=543',
    published_at: '2018-07-10T21:59:30.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1552,
    read_time: 360,
    created: '2018-07-11T06:10:11.709Z',
    score: 49.456554,
  }, {
    id: 'rgGPBO9aLN',
    title: 'Tech’s Two Philosophies',
    description: 'Google and Facebook represent one philosophy, and Microsoft and Apple represent another; tech needs both, but ultimately platforms are more important than aggregators.',
    authors: ['Ben Thompson'],
    slug: 'techs-two-philosophies-2525415731',
    url: 'https://stratechery.com/2018/techs-two-philosophies/',
    mobile_url: null,
    image_url: 'https://stratechery.com/wp-content/uploads/2018/05/Paper.stratechery-Year-One.349.png',
    published_at: '2018-05-09T14:50:33.000Z',
    site: {
      id: 'gA56VLwEP2',
      name: 'Stratechery',
      slug: null,
      language: 'en',
      hostname: 'stratechery.com',
      url: 'https://stratechery.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1738,
    read_time: 360,
    created: '2018-06-05T23:12:46.516Z',
    score: 49.080048,
  }, {
    id: '48pG2BdGxy',
    title: "Iran's blogfather: Facebook, Instagram and Twitter are killing the web",
    description: 'Hossein Derakhshan was imprisoned by the regime for his blogging. On his release, he found the internet stripped of its power to change the world and instead serving up a stream of pointless social trivia',
    authors: ['Hossein Derakhshan'],
    slug: 'irans-blogfather-facebook-instagram-and-twitter-are-killing-the-web-1673171813',
    url: 'https://www.theguardian.com/technology/2015/dec/29/irans-blogfather-facebook-instagram-and-twitter-are-killing-the-web',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/b102f097b10bae0ffd3cda7425eb50ca66cf411f/0_0_4256_2552/master/4256.jpg',
    published_at: '2015-12-29T18:30:22.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 2891,
    read_time: 660,
    created: '2018-06-05T23:04:18.855Z',
    score: 47.249435,
  }, {
    id: '2P6jxX3Epx',
    title: "Apple escalates war against Facebook, but doesn't mention it at WWDC",
    description: 'ITP2 anti-tracking and limiting Screen Time app clearly targeting Facebook and Instagram',
    authors: ['Alex Hern'],
    slug: 'apple-escalates-war-against-facebook-but-doesnt-mention-it-at-wwdc-415504263',
    url: 'https://www.theguardian.com/technology/2018/jun/05/apple-escalates-war-against-facebook-but-doesnt-mention-it-at-wwdc',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/b6c607ad08c4947d3d326a41e07dc85293c0aabc/183_88_5019_3011/master/5019.jpg',
    published_at: '2018-06-05T09:39:49.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 806,
    read_time: 180,
    created: '2018-06-06T04:03:28.941Z',
    score: 47.19244,
  }, {
    id: 'k1qEy9dEB9',
    title: 'Snapchat Launches a Colossal Expansion of Its Advertising, Ushering in a New Era for the App',
    description: "Imran Khan was an internet-focused investment banker at Credit Suisse, where, in September 2014, he orchestrated Chinese ecommerce giant Alibaba's high-profile IPO.",
    authors: ['Staff'],
    slug: 'snapchat-launches-a-colossal-expansion-of-its-advertising-ushering-in-a-new-era-for-the-app-1624878898',
    url: 'https://www.adweek.com/digital/snapchat-launches-colossal-expansion-its-advertising-ushering-new-era-app-171924/',
    mobile_url: null,
    image_url: 'https://www.adweek.com/wp-content/uploads/files/cover-snapchat-hed-2016.png',
    published_at: '2016-06-13T14:00:01.000Z',
    site: {
      id: 'VelG9qZGW5',
      name: 'Adweek',
      slug: null,
      language: 'en',
      hostname: 'www.adweek.com',
      url: 'http://www.adweek.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 3171,
    read_time: 720,
    created: '2018-06-05T23:05:23.494Z',
    score: 46.837646,
  }, {
    id: 'RdG0OpAA6g',
    title: 'Apple Hands Siri Responsibilities to Executive Poached From Google',
    description: 'Apple is handing oversight of its Siri team to new artificial-intelligence chief\nJohn Giannandrea three months after hiring him from rival Google.',
    authors: ['Tripp Mickle', 'Tripp.Mickle Wsj.Com'],
    slug: 'Apple-Hands-Siri-Responsibilities-to-Executive-Poached-From-Google-u5leUAV',
    url: 'https://www.wsj.com/articles/apple-hands-siri-responsibilities-to-executive-poached-from-google-1531261759',
    mobile_url: null,
    image_url: 'https://images.wsj.net/im-17621/social',
    published_at: '2018-07-10T22:29:00.000Z',
    site: {
      id: 'k3561Y6o2l',
      name: 'The Wall Street Journal',
      slug: null,
      language: 'en',
      hostname: 'www.wsj.com',
      url: 'https://www.wsj.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 81,
    read_time: 0,
    created: '2018-07-12T12:37:51.525Z',
    score: 46.726982,
  }, {
    id: '4m6b2q9q6l',
    title: 'Netflix won’t stream real games, but EA, Google, and Microsoft will',
    description: 'The tech world was buzzing today with a report that Netflix will stream Telltale Games’ Minecraft: Story Mode — an initiative that looked like the video subscription giant was planning …',
    authors: ['Jeremy Horwitz'],
    slug: 'netflix-wont-stream-real-games-but-ea-google-and-microsoft-will-1431246832',
    url: 'https://venturebeat.com/2018/06/13/netflix-wont-stream-real-games-but-ea-google-and-microsoft-will/',
    mobile_url: null,
    image_url: 'https://venturebeat.com/wp-content/uploads/2015/10/Minecraft-Story-Mode-Minecraft.jpg',
    published_at: '2018-06-13T20:09:37.000Z',
    site: {
      id: '2lBGBL8aJK',
      name: 'VentureBeat',
      slug: null,
      language: 'en',
      hostname: 'venturebeat.com',
      url: 'https://venturebeat.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 909,
    read_time: 180,
    created: '2018-06-14T08:20:46.828Z',
    score: 45.79212,
  }, {
    id: 'qmElAJNeaA',
    title: 'Facebook and Twitter: we can do more to protect disabled people',
    description: 'MPs question social media giants following criticism from Katie Price over abuse of son',
    authors: ['Robert Booth'],
    slug: 'facebook-and-twitter-we-can-do-more-to-protect-disabled-people-2054218776',
    url: 'https://www.theguardian.com/society/2018/jun/19/facebook-and-twitter-must-protect-disabled-people-online-more',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/1a9bac97775771941b655997a0dd9f73201744d5/255_292_3245_1946/master/3245.jpg',
    published_at: '2018-06-19T16:44:09.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 474,
    read_time: 120,
    created: '2018-06-19T17:02:04.201Z',
    score: 45.694912,
  }, {
    id: '24av88KzGB',
    title: 'After Scrutinizing Facebook, Congress Turns to Google Deal With Huawei',
    description: 'Members of Congress have begun scrutinizing Google’s relationship with China’s Huawei Technologies—roping another Silicon Valley giant into Washington’s escalating digital cold war with Beijing.',
    authors: ['Stu Woo'],
    slug: 'after-scrutinizing-facebook-congress-turns-to-google-deal-with-huawei-3038284201',
    url: 'https://www.wsj.com/articles/after-scrutinizing-facebook-congress-turns-to-google-deal-with-huawei-1528378581',
    mobile_url: null,
    image_url: 'https://images.wsj.net/im-13443/social',
    published_at: '2018-06-07T13:36:00.000Z',
    site: {
      id: 'k3561Y6o2l',
      name: 'The Wall Street Journal',
      slug: null,
      language: 'en',
      hostname: 'www.wsj.com',
      url: 'https://www.wsj.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 958,
    read_time: 240,
    created: '2018-06-07T14:20:43.853Z',
    score: 45.601437,
  }, {
    id: 'BKG3gBeGmR',
    title: 'Australia drafts laws forcing Facebook and Google to reveal encrypted data',
    description: 'Security agencies would be given access to encrypted messaging apps under bid to ‘modernise’ laws',
    authors: ['Michael McGowan'],
    slug: 'australia-drafts-laws-forcing-facebook-and-google-to-reveal-encrypted-data-974181326',
    url: 'https://www.theguardian.com/technology/2018/jun/06/planned-laws-to-force-tech-firms-to-reveal-encrypted-data',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/9363a0e4217698234c0f0fd2801bf4f7a9c113da/0_0_5420_3253/master/5420.jpg',
    published_at: '2018-06-06T07:17:40.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 541,
    read_time: 120,
    created: '2018-06-06T10:00:58.289Z',
    score: 45.540215,
  }, {
    id: '3561m34Y6o',
    title: 'How Tech Companies Are Trying to Disrupt Terrorist Social Media Activity',
    description: 'Google, Facebook, Twitter and Microsoft formed the Global Internet Forum to\nCounter Terrorism last year to prevent terrorists from exploiting their services',
    authors: ['Stuart Macdonald The Conversation Us', 'About The Author S', 'Stuart Macdonald', 'Professor Of Law', 'Swansea University.', 'The Conversation Us', 'Recent Articles'],
    slug: 'How-Tech-Companies-Are-Trying-to-Disrupt-Terrorist-Social-Media-Activity',
    url: 'https://www.scientificamerican.com/article/how-tech-companies-are-trying-to-disrupt-terrorist-social-media-activity/',
    mobile_url: null,
    image_url: 'https://static.scientificamerican.com/sciam/cache/file/281C55B7-1201-46B3-B5B2853649D0A766_agenda.jpg?w=600&h=335',
    published_at: '2018-06-26T12:00:00.000Z',
    site: {
      id: 'nrb6rmMaAg',
      name: 'Scientific American',
      slug: null,
      language: 'en',
      hostname: 'www.scientificamerican.com',
      url: 'https://www.scientificamerican.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 930,
    read_time: 180,
    created: '2018-06-28T18:07:14.746Z',
    score: 45.33727,
  }, {
    id: '7e6gd2DQGn',
    title: 'It’s time to rein in the data barons',
    description: 'Facebook, Amazon, and Google will resist attempts to restrain their market power. But for the sake of our collective prosperity and our personal privacy, it’s a fight we can’t afford to lose.',
    authors: ['Martin Giles'],
    slug: 'its-time-to-rein-in-the-data-barons-1636539000',
    url: 'https://www.technologyreview.com/s/611425/its-time-to-rein-in-the-data-barons/',
    mobile_url: null,
    image_url: 'https://cdn.technologyreview.com/i/images/reinintopper16-9_0.jpg',
    published_at: '2018-06-19T11:00:00.000Z',
    site: {
      id: '4mBaowbaAY',
      name: 'MIT Technology Review',
      slug: null,
      language: 'en',
      hostname: 'www.technologyreview.com',
      url: 'https://www.technologyreview.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 3383,
    read_time: 780,
    created: '2018-06-19T12:48:36.982Z',
    score: 44.31659,
  }, {
    id: 'mDGzk7OENl',
    title: 'The Apple-Facebook war is heating up. We may not like who wins.',
    description: 'A new rivalry between tech giants focuses on user privacy.',
    authors: ['Pete Pachal'],
    slug: 'the-apple-facebook-war-is-heating-up-we-may-not-like-who-wins-658752228',
    url: 'https://mashable.com/2018/06/05/apple-vs-facebook/',
    mobile_url: null,
    image_url: 'https://i.amz.mshcdn.com/y2MgaiQs0PGbePdthgC8s3r058w=/1200x630/2018%2F06%2F06%2Fee%2F8b38d5baae9143838e10e7d22f648bae.7479e.jpg',
    published_at: '2018-06-06T01:39:02.454Z',
    site: {
      id: 'L5KGX5jEAb',
      name: 'Mashable',
      slug: null,
      language: 'en',
      hostname: 'mashable.com',
      url: 'http://mashable.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 782,
    read_time: 180,
    created: '2018-06-06T02:00:12.465Z',
    score: 44.014336,
  }, {
    id: 'mDGzjneWGN',
    title: "'Google And Facebook Won': Old Guard Of Advertising Under Threat In Cannes",
    description: 'Internet giants’ growing control of ad spend brought a sense of change to Cannes Lions festival',
    authors: ['Jim Waterson'],
    slug: 'google-and-facebook-won-old-guard-of-advertising-under-threat-in-cannes-810058702',
    url: 'https://www.theguardian.com/media/2018/jun/22/google-facebook-won-old-guard-advertising-under-threat-cannes-lions',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/6002a19eaff50f009be841a7206bd2a762363d26/0_188_3500_2100/master/3500.jpg',
    published_at: '2018-06-22T18:03:37.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1074,
    read_time: 240,
    created: '2018-06-22T18:20:20.214Z',
    score: 43.85496,
  }, {
    id: '796Kwz2Q6M',
    title: 'Frustrated with Facebook, Google, Tesla? So are their shareholders',
    description: 'In the past week, the three companies’ investors shot down shareholder proposals seeking more accountability from the companies and their leaders.',
    authors: ['Levi Sumagaysay'],
    slug: 'frustrated-with-facebook-google-tesla-so-are-their-shareholders-695300461',
    url: 'https://www.mercurynews.com/2018/06/07/frustrated-with-facebook-google-tesla-so-are-their-shareholders/',
    mobile_url: null,
    image_url: 'https://www.mercurynews.com/wp-content/uploads/2018/06/Google-Shareholders.jpg',
    published_at: '2018-06-07T14:03:13.000Z',
    site: {
      id: 'q4m6b8WElx',
      name: 'The Mercury News',
      slug: null,
      language: 'en',
      hostname: 'www.mercurynews.com',
      url: 'http://www.mercurynews.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 698,
    read_time: 180,
    created: '2018-06-07T15:00:34.129Z',
    score: 43.704113,
  }, {
    id: 'Wy65DZb4aw',
    title: 'Global Internet Advertising Market 2018: Top players Alphabet, Facebook, Baidu, Yahoo! Inc, Alibaba, Twitter',
    description: 'Global Internet Advertising Market Research Report The recently revealed report titled Global Internet Advertising Industry 2018 Market research Explore is an in depth study providing complete analysis of the industry for the …',
    authors: ['Pepperlisa'],
    slug: 'global-internet-advertising-market-2018-top-players-alphabet-facebook-baidu-yahoo-inc-alibaba-twitter-432939319',
    url: 'https://afinancialanalysis.com/global-internet-advertising-market-2018-top-players-alphabet-facebook-baidu-yahoo-inc-alibaba-twitter/60360/',
    mobile_url: null,
    image_url: 'https://afinancialanalysis.com/wp-content/uploads/2018/06/Internet-Advertising.jpg',
    published_at: '2018-06-11T14:56:50.000Z',
    site: {
      id: '8z6DmANAGm',
      name: 'Financial Analysis',
      slug: null,
      language: 'en',
      hostname: 'afinancialanalysis.com',
      url: 'https://afinancialanalysis.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 288,
    read_time: 60,
    created: '2018-06-11T17:02:43.071Z',
    score: 43.577488,
  }, {
    id: '8z6DVOlzEm',
    title: "Google flips switch on Chrome's newest defensive technology",
    description: "With 'Site Isolation' in use, the browser should be better protected from\nSpectra-like attacks designed to steal info such as log-on credentials.",
    authors: ['Gregg Keizer'],
    slug: 'Google-flips-switch-on-Chromes-newest-defensive-technology-XrU9oGq',
    url: 'https://www.computerworld.com/article/3289786/web-browsers/google-flips-switch-on-chromes-newest-defensive-technology.html',
    mobile_url: null,
    image_url: 'https://images.idgesg.net/images/article/2018/03/code_developer_hacker_security_man_using_laptop_by_robinraj_premchand_cc0_via_pixabay-100751417-large.3x2.jpg',
    published_at: '2018-07-12T18:32:00.000Z',
    site: {
      id: 'x2ZakxR61o',
      name: 'Computerworld',
      slug: null,
      language: 'en',
      hostname: 'www.computerworld.com',
      url: 'https://www.computerworld.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 834,
    read_time: 180,
    created: '2018-07-14T06:40:17.254Z',
    score: 43.477974,
  }, {
    id: '7e6gV4zPan',
    title: 'Apple strikes blow to Facebook as it clamps down on data harvesting',
    description: 'Rules appear to target services like Onavo Protect, which claims to protect user data even as it feeds information to Facebook',
    authors: ['Olivia Solon'],
    slug: 'apple-strikes-blow-to-facebook-as-it-clamps-down-on-data-harvesting-908622714',
    url: 'https://www.theguardian.com/technology/2018/jun/13/apple-facebook-privacy-data-harvesting-onavo-app-store',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/bbca664bffc56da9a0527173be734b467594ee61/0_0_5295_3177/master/5295.jpg',
    published_at: '2018-06-14T01:10:14.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 913,
    read_time: 180,
    created: '2018-06-14T02:03:45.603Z',
    score: 43.453697,
  }, {
    id: 'z28aeM5anR',
    title: 'Technology Unlocks “Economies Of Unscale” For Small Businesses',
    description: 'Twenty years ago, small business owners lacked the tools to expand outside of their niche markets. Today, the Internet opens a flourishing global market of consumers ready and willing to engage with businesses of any size. As Patrick Collison, co-founder of Stripe, once told me, the company’s large…',
    authors: ['Contributor'],
    slug: 'technology-unlocks-economies-of-unscale-for-small-businesses-2055432894',
    url: 'https://techcrunch.com/2014/02/23/technology-unlocks-economies-of-unscale/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2014/02/shutterstock_113049826.jpg',
    published_at: '2014-02-23T23:00:07.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 849,
    read_time: 180,
    created: '2018-06-05T23:04:46.026Z',
    score: 43.071922,
  }, {
    id: 'WnaplnwaXq',
    title: 'Marqeta raised $45M led by Iconiq for payment card processing technology, reportedly at a $545M valuation',
    description: 'On the heels of payment processing startup Adyen pricing its IPO in Europe to raise $1 billion, another startup working in the area of digital payment processing has raised a significant growth round. Marqeta, a startup out of Oakland that works with businesses for payment-card related services, including instant card-based payments and issuing the',
    authors: ['Ingrid Lunden'],
    slug: 'marqeta-raised-45m-led-by-iconiq-for-payment-card-processing-technology-reportedly-at-a-545m-valuation-3700172422',
    url: 'https://techcrunch.com/2018/06/05/marqeta-iconiq/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2017/09/gettyimages-187591474.jpg',
    published_at: '2018-06-05T18:40:32.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 566,
    read_time: 120,
    created: '2018-06-06T00:04:05.075Z',
    score: 43.071815,
  }, {
    id: '8z6DLwNm6m',
    title: 'Amazon employees protest sale of facial recognition software to police',
    description: 'The workers also want Amazon to stop selling AWS services that support deportations by ICE',
    authors: ['James Vincent'],
    slug: 'amazon-employees-protest-sale-of-facial-recognition-software-to-police-3116957208',
    url: 'https://www.theverge.com/2018/6/22/17492106/amazon-ice-facial-recognition-internal-letter-protest',
    mobile_url: null,
    image_url: 'https://cdn.vox-cdn.com/thumbor/Wj1NpbtC8PEvfbDlTiGvSCnrjaQ=/0x215:3000x1786/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/10745909/acastro_180329_1777_amazon_0002.jpg',
    published_at: '2018-06-22T09:29:30.000Z',
    site: {
      id: 'QBKG3XEmR4',
      name: 'The Verge',
      slug: null,
      language: 'en',
      hostname: 'www.theverge.com',
      url: 'http://www.theverge.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 493,
    read_time: 120,
    created: '2018-06-22T11:00:07.507Z',
    score: 42.621616,
  }, {
    id: '24avg35Z6B',
    title: 'The Legendary Apple Research Group That Shaped Our World',
    description: 'Before Steve Jobs gave it the ax in 1997, the Advanced Technology Group developed some of the most influential technology of the century.',
    authors: ['Jesus Diaz'],
    slug: 'the-legendary-apple-research-group-that-shaped-our-world-776782172',
    url: 'https://www.fastcodesign.com/90176202/how-apples-advanced-technology-group-changed-our-world',
    mobile_url: null,
    image_url: 'https://images.fastcompany.net/image/upload/w_1280,f_auto,q_auto,fl_lossy/wp-cms/uploads/sites/4/2018/06/p-1-90176202-apples-advanced-technology-group-changed-the-world.jpg',
    published_at: '2018-06-19T12:15:20.000Z',
    site: {
      id: 'PWnapkWEXq',
      name: 'Co.Design',
      slug: null,
      language: 'en',
      hostname: 'www.fastcodesign.com',
      url: 'https://www.fastcodesign.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1865,
    read_time: 420,
    created: '2018-06-19T14:40:09.503Z',
    score: 42.609207,
  }, {
    id: '3561ZY1dGo',
    title: 'Aaptiv raises $22M from Amazon, Disney and more for its “Netflix for fitness”, now valued over $200M',
    description: 'Health and wellness has been one of the biggest categories for development in the tech industry, with huge range of wearable devices and connected equipment being built to track how we are moving and helping us stay fit. Now, a startup whose app offers users a selection of audio-based, personal-tra…',
    authors: ['Ingrid Lunden'],
    slug: 'aaptiv-raises-22m-from-amazon-disney-and-more-for-its-netflix-for-fitness-now-valued-over-200m-3618045289',
    url: 'https://techcrunch.com/2018/06/20/aaptiv-raises-22m-from-amazon-disney-and-more-for-its-netflix-for-fitness-now-valued-over-200m/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2018/06/Screen-Shot-2018-06-20-at-12.50.50.png',
    published_at: '2018-06-20T11:51:45.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 875,
    read_time: 180,
    created: '2018-06-20T12:00:28.362Z',
    score: 42.47744,
  }, {
    id: '5KGX3nlY6A',
    title: 'ACLU wants Amazon to stop offering surveillance technology',
    description: 'Their message is loud and clear.',
    authors: ['Kaitlin Benz'],
    slug: 'aclu-wants-amazon-to-stop-offering-surveillance-technology-2427880665',
    url: 'https://www.cnet.com/news/aclu-wants-amazon-to-stop-offering-surveillance-technology-rekognition/',
    mobile_url: null,
    image_url: 'https://cnet2.cbsistatic.com/img/R2KWo_6_liQtLpIDceOs4D7Opks=/670x503/2018/06/18/1bfd57bd-e1ba-436a-a0e4-0eb9cb1b9bb2/gettyimages-826000302.jpg',
    published_at: '2018-06-18T21:47:00.000Z',
    site: {
      id: 'QBKG3BX6mR',
      name: 'CNET',
      slug: null,
      language: 'en',
      hostname: 'www.cnet.com',
      url: 'https://www.cnet.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 331,
    read_time: 60,
    created: '2018-06-19T01:20:21.630Z',
    score: 42.448032,
  }, {
    id: '5KGXy45kEA',
    title: 'ACLU wants Amazon to stop offering surveillance technology',
    description: 'Their message is loud and clear.',
    authors: ['Kaitlin Benz'],
    slug: 'aclu-wants-amazon-to-stop-offering-surveillance-technology-25877570',
    url: 'https://www.cnet.com/au/news/aclu-wants-amazon-to-stop-offering-surveillance-technology-rekognition/',
    mobile_url: null,
    image_url: 'https://cnet2.cbsistatic.com/img/R2KWo_6_liQtLpIDceOs4D7Opks=/670x503/2018/06/18/1bfd57bd-e1ba-436a-a0e4-0eb9cb1b9bb2/gettyimages-826000302.jpg',
    published_at: '2018-06-18T21:47:00.000Z',
    site: {
      id: 'QBKG3BX6mR',
      name: 'CNET',
      slug: null,
      language: 'en',
      hostname: 'www.cnet.com',
      url: 'https://www.cnet.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 331,
    read_time: 60,
    created: '2018-06-19T14:40:58.333Z',
    score: 42.439457,
  }, {
    id: 'mDGz2jLGNl',
    title: 'Adyen aims for a $1B IPO, valuing the payments startup at up to $8.3B when it lists on June 13',
    description: 'After announcing its intention to go public in May, today Adyen published more details with the finances filled in. The Netherlands-based payments startup — which competes against the likes of PayPal and Stripe to power payment services both to online and physical retailers — said that it will be raising between €922 million and €947 million […]',
    authors: ['Ingrid Lunden'],
    slug: 'adyen-aims-for-a-1b-ipo-valuing-the-payments-startup-at-up-to-8-3b-when-it-lists-on-june-13-2051945583',
    url: 'https://techcrunch.com/2018/06/05/adyen-aims-for-a-1b-ipo-valuing-the-payments-startup-at-up-to-8-3b-when-it-lists-on-june-13/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2017/07/gettyimages-165418688.jpg',
    published_at: '2018-06-05T18:58:43.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 737,
    read_time: 180,
    created: '2018-06-06T00:04:08.031Z',
    score: 42.28493,
  }, {
    id: 'Nx6QxAeWa2',
    title: 'Amazon Workers to Jeff Bezos: Stop Weaponizing Our Tech',
    description: 'A growing tide of Silicon Valley workers are rebelling against their employers over practices they see as unethical.',
    authors: ['A Kosoff'],
    slug: 'amazon-workers-to-jeff-bezos-stop-weaponizing-our-tech-550668188',
    url: 'https://www.vanityfair.com/news/2018/06/amazon-workers-to-jeff-bezos-stop-weaponizing-our-tech',
    mobile_url: null,
    image_url: 'https://media.vanityfair.com/photos/5b2d06356cf0c55cfe0c42ca/16:9/w_1200,h_630,c_limit/amazon-facial-rekognition.jpg',
    published_at: '2018-06-22T14:27:04.451Z',
    site: {
      id: 'QmDGz2WGNl',
      name: 'Vanity Fair',
      slug: null,
      language: 'en',
      hostname: 'www.vanityfair.com',
      url: 'http://www.vanityfair.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 756,
    read_time: 180,
    created: '2018-06-22T15:40:12.762Z',
    score: 41.56872,
  }, {
    id: 'A56VO04GP2',
    title: 'Norwest just scored an interesting new partner: Google and Facebook alum Priti Youssef Choksi',
    description: 'A lot of people who’ve been working in the venture industry — even for many years — haven’t seen a true down cycle. Somewhat ironically, Priti Youssef Choksi, a newly minted VC, knows very well what one looks like. The newest partner of the multi-stage investment firm Norwes…',
    authors: ['Connie Loizos'],
    slug: 'norwest-just-scored-an-interesting-new-partner-google-and-facebook-alum-priti-youssef-choksi-550433663',
    url: 'https://techcrunch.com/2018/06/05/norwest-just-scored-an-interesting-new-partner-google-and-facebook-alum-priti-youssef-choksi/',
    mobile_url: null,
    image_url: 'https://techcrunch.com/wp-content/uploads/2018/06/banner4.jpg',
    published_at: '2018-06-06T01:11:39.000Z',
    site: {
      id: 'L5KGX5LEAb',
      name: 'TechCrunch',
      slug: null,
      language: 'en',
      hostname: 'techcrunch.com',
      url: 'https://techcrunch.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 918,
    read_time: 180,
    created: '2018-06-06T02:04:54.619Z',
    score: 41.54077,
  }, {
    id: '2P6jr2q36p',
    title: 'Amazon Employees Want Jeff Bezos to Stop Selling Rekognition to Law Enforcement, Says Report',
    description: 'They join shareholders and the ACLU in their concern.',
    authors: ['Sarah Gray'],
    slug: 'amazon-employees-want-jeff-bezos-to-stop-selling-rekognition-to-law-enforcement-says-report-1125187638',
    url: 'http://fortune.com/2018/06/22/amazon-employees-jeff-bezos-stop-rekognition-law-enforcement/',
    mobile_url: null,
    image_url: 'https://fortunedotcom.files.wordpress.com/2018/05/amazon_thumb.jpg',
    published_at: '2018-06-22T12:00:00.000Z',
    site: {
      id: '4mBaokaAYr',
      name: 'Fortune',
      slug: null,
      language: 'en',
      hostname: 'fortune.com',
      url: 'http://fortune.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 544,
    read_time: 120,
    created: '2018-06-23T01:20:33.929Z',
    score: 41.509384,
  }, {
    id: 'jLaRvY3qag',
    title: "Apple Isn't Your Friend",
    description: 'Apple has been steadily positioning itself as the anti-Facebook for a while now, and between verbal jabs aimed at the social media giant and privacy-focused product decisions, the patient goodwill campaign seems to be working. Unfortunately, Apple isn’t going to save us, and now’s the time to keep your guard up.',
    authors: ['Rhett Jones'],
    slug: 'apple-isnt-your-friend-1678119617',
    url: 'https://gizmodo.com/apple-isnt-your-friend-1826611293',
    mobile_url: null,
    image_url: 'https://i.kinja-img.com/gawker-media/image/upload/s--ADfn5lHa--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/haj3rsku1yr8cchapqw4.jpg',
    published_at: '2018-06-08T16:55:00.000Z',
    site: {
      id: 'z28ae8gEnR',
      name: 'Gizmodo',
      slug: null,
      language: 'en',
      hostname: 'gizmodo.com',
      url: 'http://gizmodo.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1977,
    read_time: 420,
    created: '2018-06-10T04:30:02.454Z',
    score: 41.3071,
  }, {
    id: 'mDGzvwQeGN',
    title: "Amazon to add over 1,000 jobs in Ireland in country's biggest staff...",
    description: 'Amazon will add more than 1,000 new jobs in Ireland over the next two years, the U.S. online retail giant said on Monday, taking its workforce to more than 3,500 in a country that continues to be a magnet for major technology firms.',
    authors: ['Editorial'],
    slug: 'amazon-to-add-over-1-000-jobs-in-ireland-in-countrys-biggest-staff-523838389',
    url: 'https://www.reuters.com/article/us-amazon-jobs-ireland/amazon-to-add-over-1000-jobs-in-ireland-in-countrys-biggest-staff-boost-this-year-idUSKBN1JE1HN',
    mobile_url: null,
    image_url: 'https://s1.reutersmedia.net/resources/r/',
    published_at: '2018-06-18T13:56:15.000Z',
    site: {
      id: 'wRdG0w6g0M',
      name: 'Reuters',
      slug: null,
      language: 'en',
      hostname: 'www.reuters.com',
      url: 'http://www.reuters.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 233,
    read_time: 60,
    created: '2018-06-19T14:40:05.814Z',
    score: 41.2782,
  }, {
    id: 'e8z6Dz3Emq',
    title: 'Why Eric Schmidt doesn’t know how Google works',
    description: 'If Google’s management style is the reason for its success, then why have the majority of initiatives at Google either failed or been financially inefficient and unprofitable?',
    authors: ['Darius Lahoutifard', 'Business Hangouts'],
    slug: 'why-eric-schmidt-doesnt-know-how-google-works-618045474',
    url: 'https://venturebeat.com/2014/11/30/why-eric-schmidt-doesnt-know-how-google-works/',
    mobile_url: null,
    image_url: 'https://venturebeat.com/wp-content/uploads/2012/04/eric-schmidt-testimony.jpg',
    published_at: '2014-11-30T20:00:57.000Z',
    site: {
      id: '2lBGBL8aJK',
      name: 'VentureBeat',
      slug: null,
      language: 'en',
      hostname: 'venturebeat.com',
      url: 'https://venturebeat.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 1110,
    read_time: 240,
    created: '2018-06-05T23:04:38.581Z',
    score: 41.150284,
  }, {
    id: '5KGXbe1jaA',
    title: 'Mapbox taps ex-Apple designer to head augmented reality efforts',
    description: 'Mapping startup Mapbox Inc said Monday that it had hired Avi Cieplinski, an veteran of Twitter and Apple who co-invented several popular iPhone features, to head up its efforts help application makers design location-based augmented reality software.',
    authors: ['Stephen Nellis'],
    slug: 'mapbox-taps-ex-apple-designer-to-head-augmented-reality-efforts-512406193',
    url: 'https://www.reuters.com/article/us-mapbox-design/mapbox-taps-ex-apple-designer-to-head-augmented-reality-efforts-idUSKBN1J718C',
    mobile_url: null,
    image_url: 'https://s4.reutersmedia.net/resources_v2/images/rcom-default.png',
    published_at: '2018-06-11T11:04:47.000Z',
    site: {
      id: 'wRdG0w6g0M',
      name: 'Reuters',
      slug: null,
      language: 'en',
      hostname: 'www.reuters.com',
      url: 'http://www.reuters.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 393,
    read_time: 60,
    created: '2018-06-12T00:40:07.228Z',
    score: 41.128574,
  }, {
    id: 'mNLEJK1akQ',
    title: 'Facebook and Twitter are being used to manipulate public opinion – report',
    description: 'Nine-country study finds widespread use of social media for promoting lies, misinformation and propaganda by governments and individuals',
    authors: ['Alex Hern'],
    slug: 'facebook-and-twitter-are-being-used-to-manipulate-public-opinion-report-1276645301',
    url: 'https://www.theguardian.com/technology/2017/jun/19/social-media-proganda-manipulating-public-opinion-bots-accounts-facebook-twitter',
    mobile_url: null,
    image_url: 'https://i.guim.co.uk/img/media/2ad601f828fd8a64af7bccf2e2241f7cd1f3c3f7/0_179_4000_2399/master/4000.jpg',
    published_at: '2017-06-19T17:57:39.000Z',
    site: {
      id: 'kW9a4BG0Ol',
      name: 'The Guardian',
      slug: null,
      language: 'en',
      hostname: 'www.theguardian.com',
      url: 'https://www.theguardian.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 965,
    read_time: 240,
    created: '2018-06-05T23:04:13.610Z',
    score: 40.989513,
  }, {
    id: 'dNx6QngG2L',
    title: 'Tech Stocks Are Hitting Highs as Economic Uncertainty Rises',
    description: 'Investors have returned to the safety and growth of the biggest technology stocks.',
    authors: ['Stephen Grocer'],
    slug: 'tech-stocks-are-hitting-highs-as-economic-uncertainty-rises-3108831056',
    url: 'https://www.nytimes.com/2018/06/05/business/dealbook/tech-stocks-economic-uncertainty.html',
    mobile_url: 'https://mobile.nytimes.com/2018/06/05/business/dealbook/tech-stocks-economic-uncertainty.html',
    image_url: 'https://static01.nyt.com/images/2017/11/20/business/dealbook/nasdaq-stock-chart-1528231626149/nasdaq-stock-chart-1528231626149-facebookJumbo.png',
    published_at: '2018-06-05T22:08:55.864Z',
    site: {
      id: 'x2Zakl61or',
      name: 'The New York Times',
      slug: null,
      language: 'en',
      hostname: 'www.nytimes.com',
      url: 'https://www.nytimes.com',
      mobile_url: 'https://mobile.nytimes.com',
    },
    language: 'en',
    word_count: 216,
    read_time: 60,
    created: '2018-06-05T23:02:05.452Z',
    score: 40.642796,
  }, {
    id: 'W9a41ly760',
    title: 'Amazon is killing the TV remote',
    description: "Amazon's new Fire TV Cube could become the new standard for watching TV.",
    authors: ['Mike Murphy'],
    slug: 'amazon-is-killing-the-tv-remote-2016255775',
    url: 'https://qz.com/1299827/amazon-introduces-the-fire-tv-cube-a-streaming-device-that-could-be-the-end-of-tv-remotes/',
    mobile_url: null,
    image_url: 'https://qz.com/wp-content/uploads/2018/06/FireTVCube_Lifestyle_1-e1528386582192.jpg',
    published_at: '2018-06-07T13:14:23.000Z',
    site: {
      id: 'Ww2EWwEey5',
      name: 'Quartz',
      slug: null,
      language: 'en',
      hostname: 'qz.com',
      url: 'https://qz.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 524,
    read_time: 120,
    created: '2018-06-07T17:42:47.555Z',
    score: 40.48449,
  }, {
    id: 'Nx6Q89ga2L',
    title: 'Tech stocks mixed after recent surge; banks lift S&P, Dow',
    description: 'Gains for Amazon and Tesla helped the Nasdaq open at a record high on Wednesday, before the index fell slightly as Facebook led a decline in the technology sector.',
    authors: ['Medha Singh'],
    slug: 'tech-stocks-mixed-after-recent-surge-banks-lift-s-and-p-dow-3379641361',
    url: 'https://www.reuters.com/article/us-usa-stocks/tech-stocks-mixed-after-recent-surge-banks-lift-sp-dow-idUSKCN1J21E8',
    mobile_url: null,
    image_url: 'https://s3.reutersmedia.net/resources/r/',
    published_at: '2018-06-06T14:33:07.000Z',
    site: {
      id: 'wRdG0w6g0M',
      name: 'Reuters',
      slug: null,
      language: 'en',
      hostname: 'www.reuters.com',
      url: 'http://www.reuters.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 493,
    read_time: 120,
    created: '2018-06-06T15:02:38.571Z',
    score: 40.391792,
  }, {
    id: 'NXGw9XKDaY',
    title: 'Lawmakers press Apple and Google to explain how they track and listen to users',
    description: 'Top members of the House Energy and Commerce Committee asked Google and Apple\nfor more information on how their smartphone operating systems collect data.',
    authors: ['Hayley Tsukayama', 'Tony Romm'],
    slug: 'Lawmakers-press-Apple-and-Google-to-explain-how-they-track-and-listen-to-users-ItAfH40',
    url: 'https://www.washingtonpost.com/ellipsis/lawmakers-press-apple-and-google-to-explain-how-they-track-and-listen-to-users/2018/07/09/07261f86-2d20-4f3b-b9ba-bd3ca19c7ccc_story.html',
    mobile_url: null,
    image_url: 'https://www.washingtonpost.com/resizer/9OO1g1mEieXUlP07_EuoHGOjTS4=/1484x0/arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/UQ3BBDEX7AI6PL3KMVK4VLVY3Q.jpg',
    published_at: '2018-07-09T00:00:00.000Z',
    site: {
      id: '3yN6dqG5KB',
      name: 'The Washington Post',
      slug: null,
      language: 'en',
      hostname: 'www.washingtonpost.com',
      url: 'https://www.washingtonpost.com',
      mobile_url: null,
    },
    language: 'en',
    word_count: 515,
    read_time: 120,
    created: '2018-07-12T12:36:57.829Z',
    score: 40.14192,
  }
];

module.exports = {
  data,
};
